### ISSUE TITLE
No Raycasting on Prey

### ISSUE THREAD

**Issue by pr0uxx** [Loop-infinity/Evolving-AI#10]
Prey does not have any sort of raycasting detection implemented. 

@Loop-infinity Do you want prey raycasting to shoot rays over 360 degrees?

**Comment by Loop-infinity** [comment]
Yup. Lets have the same number of the rays for both prey and predator. Preys will have 360 and widely separated rays and predators will have narrow fov with closely separated rays.

**Comment by Loop-infinity** [comment]
We can keep tweaking this to see different  results.

**Comment by pr0uxx** [comment]
Alright I'll make a pr for this in a bit
